language: java

services:
  - postgresql

before_install:
  - psql -c 'create database "lucys-love-bus";' -U postgres
  - mv common/src/main/resources/properties/db.properties.example common/src/main/resources/properties/db.properties
  - mv common/src/main/resources/properties/emailer.properties.example common/src/main/resources/properties/emailer.properties
  - mv common/src/main/resources/properties/expiration.properties.example common/src/main/resources/properties/expiration.properties
  - mv common/src/main/resources/properties/jwt.properties.example common/src/main/resources/properties/jwt.properties
  - mv common/src/main/resources/properties/stripe.properties.example common/src/main/resources/properties/stripe.properties
