dist: xenial
os: linux
language: java
services:
  - postgresql
addons:
  apt:
    packages:
      - python3

# This stage prepares the branch to be built and tested
before_install:
  # property configuration
  - export DIR_PROP='common/src/main/resources/properties/'
  - ./copy_properties.sh $DIR_PROP

  # creates a local database which we use to run tests
  - psql -c 'create database "lucys-love-bus";' -U postgres

# Default installation stage runs everything as below but without spotless:check
# Tests are run as mvn test -B as part of the "script" stage
install:
  - pip3 install requests
  - mvn spotless:check install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

# This stage reconfigures our property files for a production database, stripe, and emailer connection
# It then builds a JAR which we zip with our Dockerfile and Elastic Beanstalk Config
before_deploy:
  - python3 deploy.py
  - cd /home/travis/build/Code-4-Community/lucys-love-bus-backend/
  - mvn clean spotless:check install
  - zip build.zip Dockerfile service/target/service-1.0-SNAPSHOT-jar-with-dependencies.jar .ebextensions/size.config

# The resulting build.zip is deployed to Lucy's Love Bus's Elastic Beanstalk instance
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIASDHWAM4JJDE3ZW47
  secret_access_key: $AWS_EB_SECRET_KEY
  region: us-east-2
  app: llb-prod-eb
  env: llb-prod-env
  bucket: elasticbeanstalk-us-east-2-144397330194
  zip_file: "build.zip"
  on:
    repo: Code-4-Community/lucys-love-bus-backend
    branch: master
  skip_cleanup: true
