version: 2.1

jobs:
  build:
    steps: 
      run: 
        # property configuration
        - export DIR_PROP='common/src/main/resources/properties/'
        - ./copy_properties.sh $DIR_PROP

        # creates a local database which we use to run tests
        - psql -c 'create database "lucys-love-bus";' -U postgres
        
        - python3 -m pip install requests
        - mvn spotless:check install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
        
        - mvn clean test jacoco:report coveralls:report
